[package]
name = "ch06_p193_01_uart"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wio_terminal = "0.6.1" # 必須クレート
panic-halt = "0.2" # 必須クレート
atsamd-hal = "0.15.1" # シリアル通信に必要
heapless = "0.5"